apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
    kpt.dev/config-injection: required
data:
  subnetName: example
  cidr: 172.21.0.0/24
  gateway: 172.21.0.0/24
  excludeIp: 172.21.0.0..172.21.0.50
  masterIf: eth0
  macvlanMode: bridge
