apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: macvlan # kpt-set: ${subnetName}
spec:
  protocol: IPv4
  provider: macvlan.default # kpt-set: ${subnetName}.default
  cidrBlock: 172.17.0.0/16 # kpt-set: ${cidr}
  gateway: 172.17.0.1 # kpt-set: ${gateway}
  excludeIps:
    - 172.17.0.1 # kpt-set: ${gateway}
    - 172.17.0.0..172.17.0.10 # kpt-set: ${excludeIp}

