apiVersion: v1
kind: Service
metadata:
  name: emqx
  namespace: default
  labels:
    app.kubernetes.io/name: emqx
spec:
  type: ClusterIP
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
    nodePort: null
  - name: mqttssl
    port: 8883
    protocol: TCP
    targetPort: mqttssl
    nodePort: null
  - name: ws
    port: 8083
    protocol: TCP
    targetPort: ws
    nodePort: null
  - name: wss
    port: 8084
    protocol: TCP
    targetPort: wss
    nodePort: null
  - name: dashboard
    port: 18083
    protocol: TCP
    targetPort: dashboard
    nodePort: null
  selector:
    app.kubernetes.io/name: emqx
    app.kubernetes.io/instance: emqx
---
# Source: emqx/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: emqx-headless
  namespace: default
  labels:
    app.kubernetes.io/name: emqx
    helm.sh/chart: emqx-5.8.6
    app.kubernetes.io/instance: emqx
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
  - name: mqttssl
    port: 8883
    protocol: TCP
    targetPort: mqttssl
  - name: ws
    port: 8083
    protocol: TCP
    targetPort: ws
  - name: wss
    port: 8084
    protocol: TCP
    targetPort: wss
  - name: dashboard
    port: 18083
    protocol: TCP
    targetPort: dashboard
  - name: ekka
    port: 4370
    protocol: TCP
    targetPort: ekka
  selector:
    app.kubernetes.io/name: emqx
    app.kubernetes.io/instance: emqx
