apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
    kpt.dev/config-injection: required
data:
  networkName: example
  cidr: 172.21.0.0/16
