apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: generate-values
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: fn.kpt.dev|StarlarkRun|default|generate-values
source: |-
  load("krmfn.star", "krmfn")
  def set_values(resources):
    for r in resources:
      if krmfn.match_gvk(r, "v1", "ConfigMap") and krmfn.match_name(r, "kptfile.kpt.dev"):
        subnet_name = r["data"]["name"]

    for r in resources:
      if krmfn.match_gvk(r, "k8s.cni.cncf.io/v1", "NetworkAttachmentDefinition"):
        r["spec"]["config"] = '{ "cniVersion": "0.3.0", "type": "kube-ovn", "server_socket": "/run/openvswitch/kube-ovn-daemon.sock", "provider": "' + subnet_name + '.default.ovn" }'

    for r in resources:
      if krmfn.match_gvk(r, "v1", "ConfigMap") and krmfn.match_name(r, "setters"):
        r["data"]["subnetName"] = subnet_name


  set_values(ctx.resource_list["items"])
