apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: example # kpt-set: ${subnetName}
spec:
  protocol: IPv4
  provider: example.default.ovn # kpt-set: ${subnetName}.default.ovn
  cidrBlock: 172.21.0.0/24 # kpt-set: ${cidr}
  gateway: 172.21.0.0/24 # kpt-set: ${gateway}
  excludeIps:
  - 172.21.0.0/24 # kpt-set: ${gateway}
