apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  labels:
    type: "setters"
  annotations:
    kpt.dev/config-injection: required
    config.kubernetes.io/local-config: "true"
data:
  networkName: example
  clusterName: regional
  cidr: 172.21.0.0/24
  gateway: 172.21.0.0/24
